#!/usr/bin/expect -f

set timeout -1
spawn /bin/Agent.Listener configure
match_max 100000
expect -exact "> "
send -- "y\r"
expect -exact "> "
send -- "$env(TFS_URL)\r"
expect -exact "> "
send -- "\r"
expect -exact "> "
send -- "$env(TFS_USERNAME)\r"
expect -exact "> "
send -- "$env(TFS_PWD)"
expect -exact "*"
send -- "\r"
expect -exact "> "
send -- "$env(TFS_AGENTPOOL)\r"
expect -exact "> "
send -- "$env(TFS_AGENTNAME)\r"
expect -exact "$env(TFS_AGENTNAME)\r
Scanning for tool capabilities.\r
Connecting to the server.\r
Successfully added the agent\r
Testing agent connection.\r
Enter work folder (press enter for _work) > "
send -- "\r"
expect eof
